### ISSUE TITLE
Left panel is not updated after applying the leave

### ISSUE THREAD

**Issue by pankajkumar005** [pankajkumar005/Leave-Tracker-App#23]
After applying the leave, view moves to "Upcoming Leaves" but in left panel "Leave Tally" is highlighted

![image](https://cloud.githubusercontent.com/assets/4973507/8181132/12eb3734-1441-11e5-8761-a90e992ca211.png)

**Comment by pankajkumar005** [comment]
It seems, "Leave Tally" is always highlighted, irrespective of view on the right side.

**Comment by shikhaj** [comment]
done
